humanoid_nav_rl_bridge:
  ros__parameters:
    robot_config_path: "spacemit_robot/application/native/humanoid_linglong/config/linglong.yaml"
    cmd_vel_topic: "/cmd_vel"
    accepted_cmd_vel_timeout_s: 0.5
    publish_rate_hz: 20.0

    auto_fsm: false
    auto_policy: "walk"
    auto_request_period_s: 0.5
    require_zero_ready: true
    send_poweroff_on_shutdown: false

    max_vx: 0.3
    max_vy: 0.25
    max_wz: 0.5
    max_accel_vx: 0.4
    max_accel_vy: 0.3
    max_accel_wz: 0.8
